version: '3.7'

services:

    server:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend/:/backend/
        command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
        env_file:
            - ./backend/.env
        ports:
            - 8000:8000
    
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: dakotap3045@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root